apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-api-deployment
  labels:
    app: project2-main-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project2-main-api
  template:
    metadata:
      labels:
        app: project2-main-api
    spec:
      containers:
        - image: olvmky/project-two-main
          imagePullPolicy: Always
          name: project2-main-api
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: main-api-service
spec:
  selector:
    app: project2-main-api
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080

